[server]
address = "0.0.0.0"
port = 8501
enableCORS = true

[browser]
serverAddress = "0.0.0.0"
serverPort = 8501

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif" 